### PR TITLE
[V3] Update react-native-experimental-navigation to new version with PropTypes fix

### PR DESCRIPTION
**Pull request by daviscabral**
This PR is dependent of aksonov/react-native-experimental-navigation#31 (where the version is updated).

Babel presets and plugins were also updated in the process.

### CODE REVIEW

**Comment by daviscabral** [comment]
@aksonov any objection in going forward with this kind of update? That’s the maintenance of v3 that I would like to keep - that I told you about in #69.

**Comment by ujwal-setlur** [comment]
@daviscabral , don't you need to change the import statements to import reactxp-experimental-navigation in stead of react-native-experimental-navigation? For example, in Router.js:

```
import NavigationExperimental from 'react-native-experimental-navigation';
```

I would imagine this import statement would have to change to reference reactxp-experimental-navigation.

**Comment by daviscabral** [comment]
@ujwal-setlur good catch! I was under the impression I had committed those changes. I'll get those committed and pushed now.

**Comment by schlaegerz** [comment]
I tried using this branch and it doesn't seem to work. 
Router.js is doing the following:
```
const {
  RootContainer: NavigationRootContainer,
} = NavigationExperimental;
```

And the branch you are using doesn't have RootContainer defined as part of NavigationExperimental

**Comment by daviscabral** [comment]
@schlaegerz you are totally right. I know what happened - I've have in my app with a custom reducer and router - what made I miss it. My bad - I'll work in a proper fix. Probably worth to patch http://github.com/aksonov/react-native-experimental-navigation instead of moving over a totally different project.

**Comment by daviscabral** [comment]
Working to fix this right now :+1:

**Comment by daviscabral** [comment]
I am with a new local branch working in a way to bring `useNativeDriver` to the animations - but it seems that is really broken. Not sure if worth the trouble. I'll keep cleaning up stuff to react 16.0.0.

**Comment by ujwal-setlur** [comment]
Let me know if you need any help. I really want to move to react-native 0.49 and react 16, and this issue is stopping me :)

**Comment by schlaegerz** [comment]
Thank you so much! After fixing the last of the PropTypes issues and using this branch I was finally able to get it all working again.

**Comment by daviscabral** [comment]
@schlaegerz glad to know. I changed my mind about using the MS fork - it seems they made a lot of changes there to use it with Skype. Not sure if the whole work to make it functional with v3 makes sense. An upgrade to v4 sounds more sensate.

**Comment by ujwal-setlur** [comment]
@daviscabral This is not working for me. I took the latest from your ```dc-use-react-native-experimental-navigation-from-ms``` branch. I still get the following error: 


screen shot 2017-10-25 at 2 50 10 pm

Looking at the code, it seems you are still importing "PropTypes" from react, and not prop-types?

**Comment by daviscabral** [comment]
@ujwal-setlur try to remove your node_modules and clean your npm cache. I got the same issue here, and since we haven't bumped the version yet - it was still getting the same old package. Let me know if that does not work.

**Comment by schlaegerz** [comment]
There were some leftover propTypes, i branched this one myself, if you want to just test out a temporary branch  https://github.com/schlaegerz/react-native-router-flux/tree/dc-use-react-native-experimental-navigation-from-ms

**Comment by daviscabral** [comment]
Good catch! My bad! :+1:

**Comment by ujwal-setlur** [comment]
Yay, it works with this now! Thanks!

**Comment by ujwal-setlur** [comment]
@daviscabral it looks like react-native-experimental-navigation 0.28.0 uses React.PropTypes. That needs to be cleaned out as well. Bummer, so much cleanup work!

**Comment by ujwal-setlur** [comment]
@aksonov thanks! I just forked the repo to make the changes. Glad I don't have to!

@daviscabral can you update your branch to use 0.29.0?

**Comment by ujwal-setlur** [comment]
@aksonov there were duplicate require statements in two files. I have fixed that and raised a pull request: https://github.com/aksonov/react-native-experimental-navigation/pull/32

**Comment by aksonov** [comment]
Does component fails now?

**Comment by ujwal-setlur** [comment]
Yes it refuses to build because of the duplicate require statements

**Comment by aksonov** [comment]
Done, published 0.29.1

**Comment by ujwal-setlur** [comment]
Thanks!

**Comment by ujwal-setlur** [comment]
@aksonov thanks for meeting my PR. How about this PR from @daviscabral. I have tested it and it works. @daviscabral needs to update it to use 0.29.1 of react-native-experimental-navigation

**Comment by daviscabral** [comment]
I am not home now - but should be there soon to update it 👍🏻

**Comment by daviscabral** [comment]
Did some cleanup in the commits. 

@aksonov Any chance of this getting merged?

**Comment by aksonov** [comment]
@daviscabral Could you set 0.29.1 as react-native-experimental-navigation ?

**Comment by daviscabral** [comment]
Yes - sorry - forgot to update it inside the Example folder.

**Comment by daviscabral** [comment]
@aksonov Done 👍🏻

**Comment by daviscabral** [comment]
Thank you.

**Comment by ujwal-setlur** [comment]
Thanks @daviscabral and @aksonov. Will there be a new release?

Also, @aksonov, how hard is the migration from v3 to v4? I use switch which I believe is not there in v4?

**Comment by daviscabral** [comment]
@ujwal-setlur it's there already - `3.42`.

**Comment by ujwal-setlur** [comment]
@daviscabral Oh, OK. I thought 3.42 was published before your merge.

**Comment by ujwal-setlur** [comment]
@daviscabral @aksonov I just checked and 3.42.0 does **not** have this pull request. In DefaultReneder.js:

```
import React, {
  PureComponent,
  PropTypes,
} from 'react';
```

We need a 3.43.0 or 3.42.1

**Comment by aksonov** [comment]
Done, 3.43.0

**Comment by ujwal-setlur** [comment]
That was quick 👍 Thanks!

**Pull request merged**
