### PR TITLE
Feat(TabBar): add pressOpacity for TabBar

### PR DESCRIPTION
**Pull request by Swordsman-Inaction**
Add `pressOpacity` property for `TabBar`. Nice feature from `react-native-tabs`

### CODE REVIEW

**Comment by cridenour** [comment]
Thanks @Swordsman-Inaction! Can you add this to the API docs file as well?

**Comment by Swordsman-Inaction** [comment]
@cridenour Added.

**Comment by charpeni** [comment]
Thank you!

**Comment by blackxored** [comment]
Thanks for this! One less monkey-patch I have to use. 👍

**Pull request merged**
