### PR TITLE
Fix propTypes in NavBar

### PR DESCRIPTION
**Pull request by leoz**
Fix warnings related to type mismatch.

### CODE REVIEW

**Comment by sarovin** [comment]
Oops, i created a duplicate request.
@leoz can you change titleStyle PropTypes with this? 
`titleStyle: PropTypes.oneOfType([PropTypes.array, PropTypes.object])`
so we can use an array for style without warning.

**Comment by sarovin** [comment]
#688

**Comment by leoz** [comment]
Hi @sarovin , I guess our patches could be applied one on top of another as they fix different properties.

**Comment by charpeni** [comment]
Introduced by #706.

**Pull request closed without merging**
