### PR TITLE
❗️Hotfix - update react-native-experimental-navigation package

### PR DESCRIPTION
**Pull request by jonathanchrisp**
## Overview

Updated `react-native-experimental-navigation` to the latest version on the V3 branch, so that I can fix the trailing comma error which was reported and merged two months ago.

### CODE REVIEW

**Comment by aksonov** [comment]
LGTM!

**Comment by jonathanchrisp** [comment]
@aksonov thanks for the quick turnaround, if possible can you give me an ETA as to when you'll push this version to npm?

**Comment by aksonov** [comment]
Please check 3.44.0

**Comment by jonathanchrisp** [comment]
Hey @aksonov, thanks for pushing this so quickly. I've tested and found a new issue when building the project. We get a naming collision as defined below. I'm running the latest version of `react-native`.

```
Loading dependency graph...(node:45537) UnhandledPromiseRejectionWarning: Error: jest-haste-map: @providesModule naming collision:
  Duplicate module name: Sample
  Paths: /Users/jonathanchrisp/development/xxxx/xxxx/node_modules/react-native-router-flux/ReduxExample/node_modules/react-native/Libraries/Sample/package.json collides with /Users/jonathanchrisp/development/xxxx/xxxx/node_modules/react-native/Libraries/Sample/package.json
This error is caused by a @providesModule declaration with the same name across two different files.
```

Weirdly, looking at the current [v3](https://github.com/aksonov/react-native-router-flux/tree/v3) branch I can't see this ReduxExample folder. Has this been added accidentally?

**Comment by jonathanchrisp** [comment]
Just to note, upon removing the folder everything builds as expected.

**Comment by aksonov** [comment]
Probably so. Feel free to submit PR. v3 is not supported

**Comment by jonathanchrisp** [comment]
Hi @aksonov, just to make sure, I just ran `npm pack` locally and didn't get the `ReduxExample` folder added to the tar package. If possible was this added by mistake when you pused the version earlier? I can't see how this got here otherwise, are you able to check whether you had this within your directory when you published the project?

**Comment by aksonov** [comment]
Strange. Check v3.44.1 now

**Comment by jonathanchrisp** [comment]
Hey @aksonov, just pulled down and retested/rebuilt and looks to be working as expected now. Thanks again for the prompt updates, we're looking to move off version 3 soon, hopefully one day you'll be able to remove this branch! 🍻

**Pull request merged**
