### PR TITLE
Improved RNRFActions interface definition

### PR DESCRIPTION
**Pull request by jankalfus**
I've improved the RNRFActions interface definition so that the `Actions` object is indexable by key. In code, we can then use `Actions["mySuperAwesomeScene"]()` to make a transition. Better yet, you can create an enum (e.g. `Scenes`) and corresponding `getKey` function which returns scene key based on the enum value, and use it like this: `Actions[getKey(Scenes.Register)]();`

### CODE REVIEW

**Comment by sibelius** [comment]
looks good

**Comment by dalcib** [comment]
Excelent. I was trying to solve this. Thank you.

**Comment by jankalfus** [comment]
Is there an issue? Can we merge pls?

**Comment by aksonov** [comment]
@jankalfus CircleCI fails tests, could you check it?

**Comment by jankalfus** [comment]
@aksonov There is no reason why they should fail. I've changed two lines in a typescript definition file, nothing else. From the CircleCI report it looks like it ran test for a completely different commit.

**Comment by wcandillon** [comment]
@jankalfus Is it possible to have a new version of the package that publishes this change?

**Comment by charpeni** [comment]
@wcandillon It should be available in the latest release on npm (3.37.0).

**Comment by wcandillon** [comment]
@charpeni thks a lot!

**Pull request merged**
