### PR TITLE
FIX jest warnings

### PR DESCRIPTION
**Pull request by sarovin**

### CODE REVIEW

**Comment by charpeni** [comment]
Thank you @sarovin. Did you run the Example app since ? Everything is working?

It seems you updated react-native without run `react-native `

**Comment by sarovin** [comment]
@charpeni Yes, Everything is working.

**Comment by sarovin** [comment]
@aksonov Can you merge?

**Comment by charpeni** [comment]
@sarovin I'll check that soon.

**Comment by charpeni** [comment]
There seems to have an issue with the Example on Android, the project can't even build. (Fixed in #1413)

I just checked and I do not think 'react-native upgrade` had been executed, `.flowconfig` should have been changed by the upgrade.

I'm not sure this is a proper fix for Jest, all functions seems anonymous now.

I'll disable Jest testing until I have time to fix this.

**Comment by sarovin** [comment]
ok @charpeni, thank you ;)

**Comment by charpeni** [comment]
Fixed by #1422, there was an issue with `react-addons` dependencies.

**Pull request closed without merging**
