### PR TITLE
New Documentation Structure

### PR DESCRIPTION
**Pull request by adrianmc**
**For your convenience:** Click this link to see the new docs: https://github.com/adrianmc/react-native-router-flux/tree/new-docs/docs

This PR creates a new folder /docs/ which hold documentation that is a lot more organized than the super long single page that we currently have.

@aksonov, I really like your library, but I found it very hard to learn in the beginning. I felt that a lot of it was very disorganized. As a result, I added a mini-tutorial and also split the documentation into smaller more organized files and fixed some English grammar issues.

I think this will make it easier for people to learn how to use `react-native-router-flux` and hopefully we can get more contributions into making this a better documented and more powerful customizable library.

I haven't completely rewrote everything, because that will take a LOT more work. But I hope this new structure will make it easier for people to discuss and contribute.

I hope you accept my proposed changes, this took me a lot of time and effort.

### CODE REVIEW

**Comment by charpeni** [comment]
Wow good job that's really appreciate.

In my opinion, I prefer when markdown files are in caps.

Note to the collaborators that will do the merge, please use the squash option.

**Comment by codyhazelwood** [comment]
This is much easier to navigate!  Thanks!

**Comment by adrianmc** [comment]
@charpeni Wish granted! I've renamed all the Markdown files to be uppercased!

@codyhazelwood Thanks! My hope is that this will allow us to create even better documentation, helping more people get started using and playing around with RNRF.

**Comment by aksonov** [comment]
Strange, i did squash commit and merge, but still see old readme...

**Comment by aksonov** [comment]
@adrianmc Could you also submit PR to replace README.md into the root to new one?

**Comment by adrianmc** [comment]
@aksonov sure!

**Pull request merged**
