### PR TITLE
fixes #552

### LINKED ISSUE #552: undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal
Just `npm install`ed today on my project, getting this error `undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal`.

- react-native-router-flux v3.22.0
- react-native v0.23.1

### Expected behaviour

Should run without errors.

### Actual behaviour

`undefined is not an object NavigationCardStackStyleInterpolator.forHorizontal`.
image

### Steps to reproduce

1. npm install
2. run project in xcode (to device or simulator, error is the same)

I feel confident that this is related to react-native-router-flux because I downgraded to v3.1.5 and everything was fine.

My package.json looks like this: `"react-native-router-flux": "^3.1.5",`

Also posted to StackOverflow:

http://stackoverflow.com/questions/36722967/react-native-navigationcardstackstyleinterpolator-forhorizontal-undefined

### PR DESCRIPTION
**Pull request by lynndylanhurley**

### CODE REVIEW

**Comment by cridenour** [comment]
So I'm pretty sure this is because you're running 3.24 while running 0.22. 3.24 should be for 0.24+

**Comment by lynndylanhurley** [comment]
@cridenour - is 3.24 stable?

**Comment by lynndylanhurley** [comment]
Also, if react-native v0.24+ is a dependency, why is it not listed as a dependency in `package.json`? How is anyone supposed to know which version of react-native to use with this?

**Comment by cridenour** [comment]
https://github.com/aksonov/react-native-router-flux/pull/536#issuecomment-211250908 is where I'm getting my information. Probably needs to be communicated more clearly on the README.

**Comment by lynndylanhurley** [comment]
Thx @cridenour! I updated to react-native 0.24 and everything is working fine now.

**Comment by cridenour** [comment]
No problem. Just a heads up that there is a bug upstream in NavigationExperimental in 0.24 preventing type="replace"

**Comment by aksonov** [comment]
Unfortunately RN 0.24 (rnrf 3.24.0) has significant bugs with reset/ replace actions as well as re-mounting tabs during switch. So I've marked 3.22.0 as latest. Probably have to fork 3.24.0 and return master to 3.22.0... 

Pavel.

**Comment by aksonov** [comment]
@cridenour , @lynndylanhurley I'm reverting master now to 3.22 (3.24 is within separate branch now).

**Comment by lynndylanhurley** [comment]
Thanks @aksonov!

**Pull request merged**
