### PR TITLE
add option to replace <Tabs> with custom tabbar

### PR DESCRIPTION
**Pull request by evollu**
if renderTabs is provided with tabs={true}, it will render the tab bar with custom component.
This provides more options to customization and solves my problem:
1. if I want to put tab bar at top rather than bottom
2. if I want to replace TouchableOpacity with TouchableNativeFeedback or my components

### CODE REVIEW

**Comment by aksonov** [comment]
Sorry, why you can't just pass your TabBar instead? I don't want to make built-in TabBar more complex

**Comment by evollu** [comment]
Sorry I may not get you correctly. It is not changing the built-in TabBar. If you don't have renderTabs prop then the built-in one will be rendered.

**Comment by cridenour** [comment]
I thought we talked about this in #576 - you can use `component={MyTabBar}`

**Comment by andreialecu** [comment]
Sorry for hijacking this. 

How would you use this to put the TabBar at the top? I tried something similar but had to move the order of the components around in `TabBar.js`. This kind of worked, except the TabBar now shows **above** the navigation bar.

**Comment by evollu** [comment]
@cridenour you are right. passing component works. Sorry I didn't get your point in the other issue. Thanks a lot

**Pull request closed without merging**
