### PR TITLE
direction support for rn 0.24+

### PR DESCRIPTION
**Pull request by joenoon**
https://github.com/aksonov/react-native-router-flux/pull/490

This breaks < 0.24.  I thought about trying to make it backward compatible, but seems like it would get messy and, at best, not crash.  What are the compatibility expectations?

### CODE REVIEW

**Comment by sylvainbaronnet** [comment]
I guess this module can require RN 0.24 (when it's released) for next releases ? It's better than not supporting latest RN version...

**Comment by aksonov** [comment]
Great work! 0.24 is not released officially yet, so i will merge it once it is out (next Monday?), ok?

**Comment by aksonov** [comment]
Another possibility is to publish 'rc' release for the component which will work with 0.24.rc

**Comment by philipshurpik** [comment]
Thanks!

But this PR has an issue:
disabling panHandlers with panHandlers={null} stopped working

It will be better to do smth like that:
`var state = props.scene.navigationState;
 const panHandlers = state.panHandlers !== undefined ? state.panHandlers : (isVertical ?
                NavigationCardStackPanResponder.forVertical(props) :
                NavigationCardStackPanResponder.forHorizontal(props));`

**Comment by aksonov** [comment]
Close it because of #536 (that PR includes this one)

**Comment by yusufseyrek** [comment]
RN 24.0 is released but direction still not working

**Comment by aksonov** [comment]
You may try 3.24.0 version which supports RN 0.24. However you could check #557

**Comment by yusufseyrek** [comment]
Thanks a lot @aksonov you are the best!

**Pull request closed without merging**
