### PR TITLE
Add navigationBarTitleImage prop

### PR DESCRIPTION
**Pull request by filipemonteiroth**
Sometimes we need an image rather than a text on the title. This pull request adds a prop and the lib decides to show an image or a text title.

### CODE REVIEW

**Comment by filipemonteiroth** [comment]
This check that has failed is not about the code I've just pushed. How could we solve it?

**Comment by filipemonteiroth** [comment]
@sarovin @wtfil @MechanicKim @aksonov 

Could someone check this pull request?

**Comment by filipemonteiroth** [comment]
https://github.com/aksonov/react-native-router-flux/issues/1255

**Comment by aksonov** [comment]
Could you please resolve conflicts and re-send PR, I've fixed the build

**Comment by filipemonteiroth** [comment]
I'm doing it right now!

**Comment by filipemonteiroth** [comment]
@aksonov Did the merge, waiting build to complete.

**Comment by dermeck** [comment]
Hey, how can I use this prop? I tried `<Router navigationBarTitleImage={'./img/logo.png'}>` and nothing happened. :/

**Comment by ZenkStarr** [comment]
@dermeck it seems that this was not yet released on npm (the current version 3.38.0 is from March 1st, the  PR was merged on March 2nd). Theoretically, you could reference the git repo in your package.json, but this causes an Error in the packager because of a naming collision for react-native in @providesModule. @filipemonteiroth - is there this und subsequent updates haven't been published to npm yet?

**Comment by aksonov** [comment]
I've just published 3.38.1 , please check

**Comment by dermeck** [comment]
Hi, thank you both for the feedback.

Unfortunately I'm currently unable to test it yet since I got some problems with dependencies (unmet dependency bla, duplicate module name packager). :( 

I saw sb already opened issues for that.

**Comment by uuau99999** [comment]
Hello guys, I just find that version 3.38.1 leads to the naming collision for react-native. But now I need the prop navigationBarTitleImage. Can anyone help me ?

**Pull request closed without merging**
