### PR TITLE
added new switch feature - unmountScenes

### PR DESCRIPTION
**Pull request by ms88privat**
see https://github.com/aksonov/react-native-router-flux/issues/857

### CODE REVIEW

**Comment by rturk** [comment]
@ms88privat this is interesting. Have you tested this with nested scenes?

**Comment by ms88privat** [comment]
@rturk my Router is very nested and it seems to work fine.

I got three tabs in my Switch Scene. One of them is a normal Tab Scene. All working fine. There shouldn't any breaking changes, because it all depends on the new prop "unmountScene" which you have to add to your switch scene.

**Comment by joenoon** [comment]
I'm using a much older version of the Switch component due to another bug I found but could never understand.  So probably best if @aksonov and others who are familiar with the current Switch take a good look at this.

**Comment by aksonov** [comment]
LGTM

**Pull request merged**
