### PR TITLE
REFACTORING resetHistoryStack

### PR DESCRIPTION
**Pull request by sarovin**
I have fixed the function `resetHistoryStack`.
@aksonov please merge it if it's ok.

### CODE REVIEW

**Comment by sarovin** [comment]
@charpeni Now we have another error in circleci, Can you fix it, please?

**Comment by ddolheguy** [comment]
@sarovin does this PR have anything to do with this issue https://github.com/aksonov/react-native-router-flux/issues/1110?

**Comment by sarovin** [comment]
No, this is another problem..

**Comment by aksonov** [comment]
It is shame, but I've completed missed this PR, sorry... What we could do now?

**Comment by sarovin** [comment]
I cannot test if it works. I will try it this weekend ;)

**Comment by zxcpoiu** [comment]
this fixed #1870 in my case.

**Comment by duhseekoh** [comment]
Can we get this merged?

**Comment by aksonov** [comment]
@sarovin Could you please resolve conflicts?

**Comment by sarovin** [comment]
@aksonov Can you test this PR?

**Comment by aksonov** [comment]
@sarovin Thanks for PR! I can just merge if it works for you. I'm currently working on v4 and planning to stop supporting of v3 soon...

**Comment by sarovin** [comment]
@aksonov I cannot test this PR now...

**Comment by sarovin** [comment]
We can release a beta version with this PR?

**Comment by aksonov** [comment]
Sure, will do now.

**Comment by aksonov** [comment]
Check 3.41.0-beta

**Comment by sarovin** [comment]
@duhseekoh @zxcpoiu can you test this beta?

**Comment by micabe** [comment]
Hi 3.41.0-beta did not fix the issue. tab children are still rendered twice

**Pull request merged**
