### PR TITLE
Add PropTypes and update dependencies to work with react 16.0.0

### PR DESCRIPTION
**Pull request by daviscabral**
@aksonov the PR you asked for in #69.

### CODE REVIEW

**Comment by daviscabral** [comment]
@aksonov could you please bump the version too?

**Comment by aksonov** [comment]
Done

**Comment by daviscabral** [comment]
Thanks.

**Comment by ujwal-setlur** [comment]
This does not fully resolve things for me. I am on RN 0.49.3, React 16.0.0-beta.5. PropTypes has been deprecated from React and moved to prop-types. This PR addresses some of this, but not completely. react-native-router-flux depends on an old version of react-navigation-experimental which also PropTypes from react. It needs to be get fixed there as well.

**Comment by daviscabral** [comment]
@ujwal-setlur #2541 address it - and also adds some performance improvements.

**Comment by ujwal-setlur** [comment]
Thanks! Will check it out.

**Comment by schlaegerz** [comment]
Checked out your branch, it still doesn't completely work. It appears there are a few remaining propTypes declared incorrectly

**Comment by michaelstokes** [comment]
Hello,

Is this still a pending issue? 

I've noticed my app is crashing in release mode but works fine in debug?

Thanks very much!

**Comment by ujwal-setlur** [comment]
I think it should be all fixed now

**Comment by daviscabral** [comment]
@michaelstokes do you have more information about your issue? could you open a new issue with all the data from the template filled? tag me there please, so I can help you there.

**Comment by michaelstokes** [comment]
Hi @daviscabral 

Thanks, I was able to address the issue by doing the following 

https://stackoverflow.com/questions/47603791/react-native-undefined-is-not-an-object-evaluating-react2-proptypes-string/47603838#47603838

Using react-codemon, run on your projects directory

jscodeshift -t react-codemod/transforms/React-PropTypes-to-prop-types.js myapp/

This will resolve updating proptypes for your source code and any node modules.

Re-installing node modules will require running the command again it seems.

Please follow instructions over at https://github.com/reactjs/react-codemod but essentially once you've installed jscodeshift, and you've downloaded the react-codemod files as above for the various commands such as transforming React.propTypes to PropTypes and so on.

myapp/ here corresponds to my entire application project directory so the entire react-native project.

Secondly, consider the project dependencies you're using. For example in my case I was using react-native-router-flux at version 0.38.0, the app would work in debug mode, but crash in release. I attempted to upgrade to the latest beta version of 4.0.0-beta.24 and the problem was resolved.

**Pull request merged**
