### PR TITLE
Upd deps: react-navigation to beta-15, rm RN-button, upd mobx & mobx-react

### PR DESCRIPTION
**Pull request by kesha-antonov**

### CODE REVIEW

**Comment by aksonov** [comment]
Please update also yarn.lock, also react-navigation.beta.17 was published... Maybe we could use something like '*' to install latest beta automatically?

**Comment by kesha-antonov** [comment]
@aksonov Ok! one moment.

There was style issue with navBar in beta.16. react-navigation team fixed it

Also I'm not confident enough in react-navigation usage or RNRF source code to be sure if it's a good idea or we should manually check every release of react-navigation before update.

**Comment by kesha-antonov** [comment]
What do you think about to update mobx & mobx-react?
screen shot 2017-11-04 at 21 03 33

**Comment by kesha-antonov** [comment]
I've looked through mobx changelog. Nothing breaking

**Pull request merged**
