### PR TITLE
Hide navbar programmatically

### PR DESCRIPTION
**Pull request by onrige**
According to this issue #2441 and this commit (https://github.com/aksonov/react-native-router-flux/commit/29090461469d4eb907072c63e9881f99205fab73) I am adding this functionallity again. I was trying to catch the issue when NavBar was hiding inside Drawer but I didn't succeed. May be I don't know something but according to the React Navigation docs it's not possible to put NavBar inside Drawer. @aksonov could you provide more detailed example for me to catch this error? As I said in commit comment - there are a lot of people that need this functionality so we need to resolve this problem.

### CODE REVIEW

**Comment by thiemo--bleeken** [comment]
please merge

**Comment by aksonov** [comment]
Can you just check Example project with your PR? You will see no drawer button there, sorry, I can't break this.

just replace
```
    "react-native-router-flux": "file:../",
```
to
```
    "react-native-router-flux": "github:aksonov/react-native-router-flux#1364b111cff4fa218c9521e13a780e1228a6a708",
```
within `Example/package.json` to reproduce

**Comment by onrige** [comment]
Fine. So please have a look at the last update. There was a problem with hiding `Drawer` because of `hideNavBar` property (child inheritance). It was fixed by just removing this property from `Drawer` child (`Scene` component in case of Example project) and now all works good. I am also added an example to TabView component with toggle NavBar functionality.

**Comment by aksonov** [comment]
Yes, it still has problems - just tap "next screen for tab2_1" and you will not see "back" nav button.

**Comment by aksonov** [comment]
@onrige Please check latest master, I hope I fixed that issue and your code to Example/navigationStore. Feel free to reopen if you have any bugs.

**Comment by SurpassRabbit** [comment]
If I want to hide hideNavBar, the first success, the second failed.

```
_editPress = () => {
this.setState({
            hideTabBar: !this.state.hideTabBar
            }, () => {
                Actions.refresh({
                    hideTabBar: this.state.hideTabBar
                });
            }
        );
}
```

**Pull request closed without merging**
