### PR TITLE
Upgrade react-native-tabs to be compatible with >=RN25

### PR DESCRIPTION
**Pull request by sibeliusseraphini**
Upgrade devDeps
move scripts to the bottom of package.json to be easy check on terminal

### CODE REVIEW

**Comment by aksonov** [comment]
Could you PR it to 0.26-wip branch? We are going to apply 0.26-wip to master once 0.26 will be released

**Comment by charpeni** [comment]
@aksonov CircleCI seems unlinked, can you check this?

**Comment by aksonov** [comment]
@charpeni i don't know why it is not running - i definitely see CircleCI in the list of linked services...

**Comment by aksonov** [comment]
removed and added circleci again, let's check future PRs...

**Comment by charpeni** [comment]
@aksonov Weird, maybe if you trigger a manual build from CircleCI panel.

Is that possible to give me rights on CircleCI, if you want to ?

**Comment by aksonov** [comment]
i don't know how to do it, i even don't see how to trigger manual build there. weird interface.

**Pull request closed without merging**
