### PR TITLE
Updated API Documentation

### PR DESCRIPTION
**Pull request by mcabs3**
- Lightbox w/ basic example
- Modal w/ basic example
- Actions function descriptions
- ActionConst descriptions

### CODE REVIEW

**Comment by aksonov** [comment]
Could you fix conflicts?

**Comment by mcabs3** [comment]
Sorry about that, conflicts resolved.

**Comment by aksonov** [comment]
@mcabs3 Thanks! Could you please check mobx demo I've just prepared? Maybe you will find something new, your feedback is very important for me.

**Comment by mcabs3** [comment]
I can most certainly give it a go! Is it in master? Maybe we refactor the example project to be in a parent examples folder? I can make one for redux as well.

**Comment by aksonov** [comment]
Is it in separate repo (fork of react-native-starter-app):
https://github.com/aksonov/react-native-starter-app

**Comment by themakerman** [comment]
@mcabs3 Can you please do example for a Drawer as well?

**Pull request merged**
