### PR TITLE
add props "hideTabBar" to "Route"

### PR DESCRIPTION
**Pull request by jungsoo108**
TabBar Router
--Navigation Router
----Route1
----Route2 - tab bar must hide 

add some code, for upside case.

use <Route hideTabBar={true} component={....}}/>

### CODE REVIEW

**Comment by aksonov** [comment]
Could you give me use case? I don't want to make the component more complex. Currently component doesn't know anything about 'tab bar'. Why you can't just push from tab route defined from root router? This way tab bar should not be shown for that route.

**Comment by aksonov** [comment]
Could you just fix it within TabBar:
The problem that route.props.hideTabBar is not passed for Actions call below. pass it and check how it works.
    onSelect(el){
        if (!Actions[el.props.name]){
            throw new Error("No action is defined for name="+el.props.name+" actions:"+JSON.stringify(Object.keys(Actions)));
        }
        if (el.props.selected && Actions[el.props.defaultRoute]) {
          Actions[el.props.defaultRoute]();
        } else {
          Actions[el.props.name]();
        }
        InteractionManager.runAfterInteractions(() =>
            this.setState({hideTabBar: el.props.hideTabBar}));
        return {selected: true};
    }

**Comment by jungsoo108** [comment]
list view (tab bar not hidden), press row
-> push item detail view (tab bar not hidden), press show map button
-> push map view(tab bar hidden)

i try push map view in root router, and encount problem after pop.
after pop map view, Actions.currentRouter is root router not router of item detail view.
so Actions.pop() on item detail view not working.

i think hideTabBar props of Route is one of solution.

if that is not good, help me, give another solution.

**Comment by aksonov** [comment]
@jungsoo108 I've already gave direction above - use something like Actions[el.props.name]({hideTabBar:el.props.hideTabBar})  within onSelect method, have you tried it?

**Comment by aksonov** [comment]
Okey, I've fixed it by myself in way i've described above, please check (version 2.1.9)

**Comment by jungsoo108** [comment]
today, i see your comment and code.
sorry for late feedback.

your commited code is good, and it is really helpful for my app
thank you

**Pull request closed without merging**
