### PR TITLE
renderRightButton and renderLeftButton takes selected component as argument

### PR DESCRIPTION
**Pull request by jondot**
Including the selected child lets the renderRight and Left buttons be able to render based on the child's state.

```javascript
  renderRightButton={(props)=>{ <RightButton item={props.item}/> } }
```
This can help with item counts, save/create state for items that are
existing vs new, and more.

Right now this uses 'selected' which includes the entire component,
it would probably be more suitable to include just the props of that
component but I'm not sure that's possible at that point in time.

Additionally, this should provide a way to solve:

* https://github.com/aksonov/react-native-router-flux/issues/213
* https://github.com/aksonov/react-native-router-flux/issues/478

### CODE REVIEW

**Comment by AlexDM0** [comment]
Could we also do insert this in the renderBackButton to fix #460 ? I wanted to make a pull myself but if you're doing it anyway might as well add the selected to the renderBackButton here :)

**Comment by jondot** [comment]
Sure, I've read #460, would `renderBackButton(selected)` help?

**Comment by AlexDM0** [comment]
Yes. Granted the methods need to be adapted but we'd have what we'd need I think.

**Comment by jondot** [comment]
Should be good now.
This solution in general covers some of the cases, but for some, it's not enough sadly.
It might be worth to watch this https://github.com/ericvicenti/navigation-rfc/issues/70 meanwhile.

**Pull request merged**
