### PR TITLE
Fix for #2023 - Navigation 'back' button won't render on Android

### PR DESCRIPTION
**Pull request by diegocouto**
In order to properly show the navbar left actions, the absolute positioning isn't used on Android devices.

This is my first contribution, so maybe I'm not following the right protocol! Please, let me know if something is wrong or can be improved. 😄

### CODE REVIEW

**Comment by aksonov** [comment]
Thanks! Unfortunately circleci didn't run, I've fixed it, could you just commit something to run eslint/tests ?

**Comment by aksonov** [comment]
Maybe you could look also #2038?

**Comment by diegocouto** [comment]
@aksonov I can reproduce this same issue described on #2038. I'm working on it right now. 😉

**Comment by diegocouto** [comment]
@aksonov I have added the backHandler to the App component on the Router, but I'm probably getting something wrong about accessing the index of the current scene.

The original:
``` javascript
const App = observer(props => {
  const AppNavigator = props.navigator;
  return (
    <AppNavigator navigation={addNavigationHelpers({ dispatch: navigationStore.dispatch, state: navigationStore.state })} />
  );
});
```

Is now defined as:
``` javascript
@observer
class App extends Component {
  componentDidMount () {
    BackHandler.addEventListener('hardwareBackPress', this.onBackPress);
  }

  componentWillUnmount () {
    BackHandler.removeEventListener('hardwareBackPress', this.onBackPress);
  }

  onBackPress = () => {
    if (navigationStore.state.index === 0) {
      return false;
    }

    navigationStore.pop();
    return true;
  }

  render () {
    const AppNavigator = this.props.navigator;
    return (
      <AppNavigator navigation={addNavigationHelpers({ dispatch: navigationStore.dispatch, state: navigationStore.state })} />
    );
  }
}
```

The issue here is that `navigationStore.state.index` is always `0`. Do you have an idea about what is going on?

Regarding #2038, I think that we would only have to update the docs. To make it work on android:

1. It's important to set `showIcon` on the tabbar root scene. Icons are disabled on Android by default, [as stated here](https://reactnavigation.org/docs/navigators/tab#tabBarOptions-for-TabBarTop-default-tab-bar-on-Android).

2. Instead on defining a scene like:
``` javascript
<Scene 
  key='home' 
  component={Home} 
  title='Home'
  iconName='ios-home'
  icon={TabIcon} hideNavBar />
```

The right way to do it now is:
```javascript
<Scene 
  key='home'  
  component={Home} 
  title='Home'
  tabBarIcon={() => (<TabIcon iconName={'ios-home'} />)} />
```

**Comment by hofuchi** [comment]
How about something where if the scenes don't change: exit the app
for your `onBackPress()`
```javascript
onBackPress = () => {
  navigationStore.pop();
  if (navigationStore.currentScene === navigationStore.prevScene) {
    return false; // Exit the app if you're at the root scene
  } else {
    return true; // Keep the current popped scene
  }
}
```

**Comment by diegocouto** [comment]
Thanks for all your help, @hofuchi! I've followed the approach you suggested and everything seems fine.

**Comment by aksonov** [comment]
LGTM!

**Pull request merged**
