### PR TITLE
Pass props down to child components

### LINKED ISSUE #1434: Props not passed from tab scene to sibling scene
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.36
- react-native v0.37

### Expected behaviour
object props are passed to scene like so 
```
Actions.myScene({foo: {bar:"baz"}})
```
### Actual behaviour
the props are not showing up in myScene

there is another issue that was closed #1390 for no reason. There were many breaking changes in RN36,37. Anyone else seeing their entire app break suddenly?

### PR DESCRIPTION
**Pull request by DonnieWest**
Fixes #1434

### CODE REVIEW

**Comment by DonnieWest** [comment]
Any word on this pull request? If I'm doing something wrong, please let me know :)

**Comment by tmaximini** [comment]
thanks @DonnieWest - this fixes also #563 (tab routes get params). it also fixes the 3 skipped tests in `test/Reducer.test.js` so you might actually remove the skipping as part of this PR.
👍 
It does make another test fail though ('switches to a correct tab on JUMP').
it could be fixed by modifying the test to `expect(current.key).to.eq('hello_0_hello_');` (so all pass but I am not sure if that is desired behaviour, I am not understand all internal behaviour of this lib yet) maybe @aksonov can jump in.

It would be very cool if this fix landed as I suppose lots of people get frustrated when the expected behaviour (props are passed via `Action.whatever(props)`) is not working anymore in a TabBar scenario.

**Comment by aksonov** [comment]
@DonnieWest sorry for the delay. Could you please make sure that all tests are passing and re-submit this PR? We have installed Travis CI, so tests should be run automatically now.

**Comment by DonnieWest** [comment]
@aksonov fixed the tests and rebased :)

**Comment by DonnieWest** [comment]
@aksonov any word here? If there are any issues just let me know :)

**Comment by DonnieWest** [comment]
@aksonov sorry to continue to bother you, but, is there anything I can do to get this merged in?

**Pull request merged**
