### PR TITLE
Fix some eslint errors

### PR DESCRIPTION
**Pull request by charpeni**
✖ 1023 remaining problems (1011 errors, 12 warnings)

### CODE REVIEW

**Comment by aksonov** [comment]
Is there any way to check PRs before merge to comply with code style? I've added you as collaborator.

**Comment by aksonov** [comment]
Sorry, i had to revert, because it brakes things... Maybe we need to have strong unit test coverage before such big changes...

simulator screen shot 25 apr 2016 10 16 41

**Comment by charpeni** [comment]
> Is there any way to check PRs before merge to comply with code style?

@aksonov Yes with CI from CircleCI, we will implement this after all eslint errors has been fixed.

Sorry I didn't notice the props from Modal, yeah I will do some testing with all components before submitting a pull request.

**Comment by aksonov** [comment]
@charpeni Is there any automatic tool to do all these changes (so i could do it by myself)? I'm about to commit now some improvements for navbar (with old eslint issues), so your changes will have conflict...

**Comment by charpeni** [comment]
Unfortunately, I do not believe that such tools exists.

I think for a project moving as fast we should only fix one file at time and do a pull request with solid test coverage. Don't worry with it, I will redo.

**Pull request merged**
