### PR TITLE
Added DrawerExample

### PR DESCRIPTION
**Pull request by Froelund**

### CODE REVIEW

**Comment by aksonov** [comment]
It looks great, but could you add it to existing Example (tab bar screen) to switch tab1..tab5 ? I don't want to have two example projects because i will have to support both for any fixes/changes.

**Comment by Froelund** [comment]
@aksonov I just added support to toggle the drawer in the default Navbar. I will merge the DrawerExample into the existing Example project.

**Comment by aksonov** [comment]
Great!

**Comment by aksonov** [comment]
@Froelund Sorry, it doesn't work properly for me - i see that button at start screen and all titles within tab bar are hidden (issue #421)

**Comment by aksonov** [comment]
Improved Example with Drawer

**Pull request merged**
