### PR TITLE
Fix checkPropertiesEqual

### PR DESCRIPTION
**Pull request by barakcoh**
Hi

Thought I'd take a stab at fixing this as per the `WARN` comment above it. 

In our case, we pass quite a few props in navigation calls, including arrays and functions. The `!==` check fails for those, allowing for the double-tap effect mentioned  in https://github.com/aksonov/react-native-router-flux/issues/384

The proposed solution is to use lodash's [isEqual](https://lodash.com/docs/4.17.4#isEqual) which provides a solid equality check that should suffice for most cases. `isEqual` is bundled separately to prevent bloating RNRF.

Additionally to `isEqual` I also opted to exclude checking functions altogether, as those are usually generated inline as part of the navigation call, failing `isEqual` as well.

Thoughts?

### CODE REVIEW

**Comment by Naoto-Ida** [comment]
This is great. I have the same issue of double calls to Actions which cause two pushes to happen.

**Comment by barakcoh** [comment]
@aksonov are you interested in merging my fix? I'll re-open the PR w/ the just 1st [commit](https://github.com/aksonov/react-native-router-flux/pull/1561/commits/33d5ec3a203d5fb8cbb975d7ae66c04d4a33c54b) if you are

**Comment by aksonov** [comment]
@barakcoh Yes, I'm interested

**Comment by aksonov** [comment]
Could you please resolve conflicts and re-send PR, I've fixed the build

**Comment by barakcoh** [comment]
Closing in favor of https://github.com/aksonov/react-native-router-flux/pull/1682

**Pull request closed without merging**
