### PR TITLE
Added a way to know the nav bar dimensions using the refresh action.

### PR DESCRIPTION
**Pull request by SudoPlz**
I'm creating this pull request to add the feature I requested in : https://github.com/aksonov/react-native-router-flux/issues/561

### CODE REVIEW

**Comment by SudoPlz** [comment]
Ok check this out and let me know if it is correct, I can now get the dimension of the nav bar in my reducer like so:

    const reducerCreate = params=>{
                const defaultReducer = Reducer(params);
                return (state, action)=>{

                  switch(action.type){
                    case "refresh":
                      console.log("Nav bar dimensions:",action.navBarDimensions.height); 
                      break;
                    default:
                      break;
                  }
                  return defaultReducer(state, action);
                }
            };

**Comment by aksonov** [comment]
Why you need custom reducer? Current scene will get navBarDimensions property.

**Comment by SudoPlz** [comment]
Hmm sure but I'm new to react-native-router-flux, how would I access it otherwise?

**Comment by aksonov** [comment]
Oh, if you need to access it from your reducer, not from your scene component, then you did right.

**Comment by rturk** [comment]
Why do you need this? I don't know about your app but storing dimensions in redux doesn't seems to be best practice.

**Comment by aksonov** [comment]
agree with @rturk

**Comment by SudoPlz** [comment]
Well then what should I do, would `this.props. navBarDimensions` work in any Schene now?

**Comment by aksonov** [comment]
Good question, i'm not sure. It will 100% work for current scene when layout is changed, but for other scenes it will be lost probably. Let me think about it.

**Comment by SudoPlz** [comment]
`this.props.navBarDimensions` is nowhere to be found at the moment (answering my own question above). null null null

**Comment by aksonov** [comment]
Maybe storing nav bar dimensions in redux is only way...
Here is one solution:
1. don't use 'refresh' but your redux dispatch
2. connect RNRF Router to your redux.
3. all properties you passed to Router from 'connect', will be globally available across all scenes

**Comment by rturk** [comment]
@SudoPlz can you detail your use case, why you need dimensions?

We can explore it at Gitter. I have a fairly complex App and I've managed to make it work only using flexbox, padding, and margin in the root View of each component

Overall IMO this package is a navigation stack. Adding rendering, view, features will diverge from it's core purpose

**Comment by aksonov** [comment]
@rturk I don't have different height for navbar, but probably will do (smaller height for landscape, for example). One usage i see now is setting top:HEIGHT within my scenes to avoid its overlapping by navbar. 
In my current app it is just fixed (equal to navbar height), but what i can do it navbar height is flexible?

**Comment by SudoPlz** [comment]
Ok this comment is so confusing to me right now. 

This is pretty much my `init.js` file at the moment:

      /**
      *
      * ## Initial state
      * Create instances for the keys of each structure in placeAVote
      * @returns {Object} object with 4 keys
      */
      function getInitialState() {
        const _initState = {
          auth: new authInitialState,
          device: (new deviceInitialState).set('isMobile',true),
          global: (new globalInitialState),
          profile: new profileInitialState,
          router: new routerInitialState
        };
        return _initState;
      }


let Example = React.createClass( {
          render() {


            const store = configureStore(getInitialState());

            //Connect w/ the Router
            const Router = connect()(RNRF.Router);

            // configureStore will combine reducers from Example and main application
            // it will then create the store based on aggregate state from all reducers


            var self = this;
            var renderRtBtn = function renderRtBtn(){
              return
            }
            const reducerCreate = params=>{
                const defaultReducer = Reducer(params);
                return (state, action)=>{

                  switch(action.type){
                    case "push":
                      store.dispatch(navigateState(action.key));    //I navigate to the state I want to go using my action creator (uses Actions.ScheneName on the background)
                      break;
                    case "back":
                    case "BackAction":
                      store.dispatch(navigateToPreviousState());    //I navigate to the previous state using my action creator (uses Actions.pop on the background)
                      break;
                    case "refresh":
                      console.log("Nav bar height:", action.navBarDimensions.height); 
                      store.dispatch(setNavBarDimensions(action.navBarDimensions));
                      break;
                    default:
                      break;
                  }
                  return defaultReducer(state, action);
                }
            };

            // let backButtonImg = ()=><Image source={require("../assets/back_chevron.png")} style={{padding: 8,backgroundColor:'red'}}></Image>;
            //
            // <Scene key={ScheneKeys.LOGIN} type="push" title="Sign In" navigationBarStyle={{backgroundColor:Colors.primaryColor}} backButtonImage={backButtonImg} renderRightButton={()=><RightPavLogo/>}>
            // setup the router table with App selected as the initial component

            // when the hideNavBar is true we see the right button but not the left, and the opposite.
            return (
              <Provider store={store}>
                <Router hideNavBar={false} createReducer={reducerCreate} sceneStyle={{backgroundColor:'#F7F7F7'}} >
                  <Scene key="modal" component={Modal} >
                    <Scene key="root" navigationBarStyle={{backgroundColor:Colors.primaryColor}}  titleStyle={{color:Colors.mainTextColor, fontFamily:"Whitney"}}>
                      <Scene key={ScheneKeys.ONBOARDING} direction="vertical" component={Onboarding} type="replace" hideNavBar={true} />
                      <Scene key={ScheneKeys.LOGIN} component={EmailSignIn} hideNavBar={false} title="Sign In" type="push" renderBackButton={()=><BackBtnImg/>}  renderRightButton={()=><RightPavLogo/>}/>
                      <Scene key={ScheneKeys.REGISTER_STEP_1} component={EmailSignUpStep1} type="push" hideNavBar={true} />
                      <Scene key={ScheneKeys.REGISTER_STEP_2} component={EmailSignUpStep2} type="push" hideNavBar={true} />
                      <Scene key={ScheneKeys.REGISTER_STEP_3} component={EmailSignUpStep3} type="push" hideNavBar={true} />
                      <Scene key={ScheneKeys.REGISTER_STEP_4} component={EmailSignUpStep4} type="push" hideNavBar={true} />
                      <Scene key={ScheneKeys.TOPIC_PICK} component={TopicPick} schema="modal" type="push" hideNavBar={true} />
                      <Scene direction="vertical" key={ScheneKeys.NEWSFEED} title="News Feed" hideNavBar={true} panHandlers={null} duration={1} tabs={true} initial={true}>
                            <Scene key={ScheneKeys.TAB_NEWS} title="News Feed" component={NewsFeed} icon={TabIconFactory} navigationBarStyle={{backgroundColor:Colors.primaryColor}}  titleStyle={{color:Colors.mainTextColor, fontFamily:"Whitney"}}/>
                            <Scene key={ScheneKeys.TAB_NOTIFS} title="Notifications" component={NewsFeed} icon={TabIconFactory} navigationBarStyle={{backgroundColor:Colors.primaryColor}}  titleStyle={{color:Colors.mainTextColor, fontFamily:"Whitney"}} notifications={["a notification", "another notification"]}/>
                            <Scene key={ScheneKeys.TAB_PROFILE} title="Profile" component={Profile} icon={TabIconFactory} navigationBarStyle={{backgroundColor:Colors.primaryColor}}  titleStyle={{color:Colors.mainTextColor, fontFamily:"Whitney"}} initial={true}/>
                      </Scene>
                    </Scene>
                  </Scene>
                </Router>
              </Provider>
            );
          }
        });
        /**
        * registerComponent to the AppRegistery and off we go....
        */

        AppRegistry.registerComponent('ExampleApp', () => Example);

@rturk The reason I need the dimension of the navigation bar is because I want to know its height, so that I can start rendering my schene children below it. If otherwise some of my children will be hidden beneath the navigation bar. I have to specifically set my View to start at `top= navigationBar.height`.

@aksonov you said:
1. don't use 'refresh' but your redux dispatch
But the Actions.Refresh() call is currently within the `react-native-router-flux` code, so I cannot use my own redux dispatch within there can I?

2. connect RNRF Router to your redux.
I think I have that in my code in line: `const Router = connect()(RNRF.Router);` but I neeever really understood how it works. I NEVER managed to get dispatches from RNRF directly within my own reducers.

3. all properties you passed to Router from 'connect', will be globally available across all scenes
Would you please mind giving a line of code or 2 as an example to this statement?

**Comment by aksonov** [comment]
Maybe @rturk has better solution for it, i would listen it too.

**Comment by aksonov** [comment]
1. You may use your own NavBar, and dispatch redux there, right?
2. connect(state=>({navBarHeight:state.navbar.navBarHeight})(RNRF.Router) will pass navBarHeight prop to all your scenes (but you should store it within your navbar reducer first)

**Comment by rturk** [comment]
@aksonov @SudoPlz 
I'm using my own NavBar so have more control over he UI. Also trying to follow redux best practices, this means that I only store app data and app state in the redux store. 

Within my ownNavBar I'm listening to app state changes. If the app rotates I simply update the internal state of the NavBar height. Currently I only have two heights one for portrait one for landscape.

Also I wouldn't recommend using `top` for layout. Instead I'm using a View with a `padding` as wrapper for my content. React Native Virtual DOM is smart and will convert this to a single Native Object. The benefit of this is that different than top this will look much better for views that are rotated 

<View style={padding:navBarHeight}>
 ...content
</View>

**Comment by SudoPlz** [comment]
@rturk Teach me sensei! Could I please see some code with this. Trying to style views using flexbox is already hard enough for me, would you be kind enough to share some code so that I can see your custom NavBar and how you implement this?

**Comment by rturk** [comment]
@SudoPlz I'm OOTO with no access to my code. I'll share something mid next week.

**Comment by sarovin** [comment]
I have the same prolem because the height of NavBar changes from IOS to Android and i want manage it in each screen.

**Comment by SudoPlz** [comment]
So still no solution to this..

**Pull request closed without merging**
