### PR TITLE
Add 'leftToRight' direction support

### PR DESCRIPTION
**Pull request by stephy**
This will allow users to choose 'leftToRight' direction.

Ex:
```javascript
<Scene key="settings" component={Settings} direction="leftToRight" title="Settings"/>
```

### CODE REVIEW

**Comment by aksonov** [comment]
LGTM

**Comment by aksonov** [comment]
@stephy Could you please add new mode to docs?

**Comment by wrousseau** [comment]
@stephy Hi ! What is the difference with the standard direction used by default ?

**Comment by stephy** [comment]
@wrousseau correct me if I am wrong, but the default direction is from right to left. For my app I really wanted from left to right. Since I added this feature to my app, I figure I would just do a PR as other people may want it from left to right as well. Is there a way to do navigate from left to right? I could not find it.

**Comment by stephy** [comment]
@aksonov I will do that now.

**Comment by wrousseau** [comment]
@stephy Alright, got it. I feel like the name could be confusing though because locale whose transitions between scenes are supposed to be following that direction are usually called "right to left" locales. There is actually some work being done on React Native to support rtl languages

**Comment by stephy** [comment]
@wrousseau I see what you mean, I guess that can really get confusing. I could change the name to 'horizontalLeftToRight'. What do you think?

**Comment by joenoon** [comment]
I haven't been able to try this PR yet so I might not understand exactly what we're discussing (i.e. feel free to ignore me if this doesn't make sense).  But if it does what I'm guessing, then what about: `appearFromLeftToRight`

**Comment by stephy** [comment]
@joenoon I think that's a great suggestion

**Pull request merged**
