### PR TITLE
Fix flickering white borders on scene transitions

### LINKED ISSUE #1460: White lines flickering around edges during transitions
### Version
Tell us which versions you are using: 

- react-native-router-flux v3.37.0
- react-native v0.37.0

### Expected behaviour
There would be no white lines flickering.

### Actual behaviour
I'm aware of this as being an issue in other places ([here](https://github.com/wix/react-native-navigation/issues/14) and [here](https://github.com/facebook/react-native/issues/3375)) however all of the solutions are about styling the `Navigator` component which is something that isn't exposed with this plugin. I haven't been able to find anything specific to `react-native-router-flux` that applies a solution. I saw someone had made a [commit](https://github.com/lananelson/react-native-router-flux/commit/66afc4885036a31d1645319178626221ea7eba82#diff-07ab94a626d050c4a73fb7272713b477) on a fork which looks similar to the solutions I've read about elsewhere but didn't know if it had actually made it back into the build.

See this video for an example: https://www.dropbox.com/s/08vxhuka1svn10o/white-flickering-during-transitions.mov?dl=0

### Steps to reproduce
1. Create an app with black backgrounds
2.Transition between scenes and notice the edges

### PR DESCRIPTION
**Pull request by timkendall**
Fixes #1460

### CODE REVIEW

**Comment by joenoon** [comment]
@timkendall Would this fix still work if the `style, styles.navigationCard` order was changed to `styles.navigationCard, style`? I'm thinking otherwise `getSceneStyle` can't be used to override `backgroundColor`

**Comment by timkendall** [comment]
@joenoon Oh nice good catch. Yep I changed the order and the fix still works 👍

**Comment by joenoon** [comment]
@timkendall awesome.  Only other question is what does this do to the "out of the box" rendering?  Is there another view already applying a solid background, or by default are apps going to look broken until they apply a background manually?

I'm a little behind on this project so feels wrong for me to merge without having someone more current verify it.  Maybe @charpeni could or knows who should verify and merge?

**Comment by timkendall** [comment]
@joenoon I'm honestly not too familiar with the project either so not sure.

**Comment by edencakir** [comment]
Great PR, can you guys merge?

**Comment by valerybodak** [comment]
When this issue will be resolved? Please fix it. Thank you. 
My version is: "react-native-router-flux": "3.38.0"

**Comment by valerybodak** [comment]
Hi, guys

I have finally found temporary workaround for remove ugly white borders on scene transitions. I have changed **backgroundColor** in animatedView's style in DefaultRenederer.js file:

_\node_modules\react-native-router-flux\src\DefaultRenederer.js_

const styles = StyleSheet.create({
  animatedView: {
    flex: 1,
    **backgroundColor: '#YOUR_COLOR',**
  },
  sceneStyle: {
    flex: 1,
  },
});

It works for me!

**Comment by aksonov** [comment]
I'm really sorry about missing this PR. Unfortunately I have available time only recently and completed v4 beta based on React Navigation. Feel free to submit PRs for v4 now. I promise I will not miss them again.

**Pull request closed without merging**
