### PR TITLE
Fix not available navigationState and onNavigate in Modal

### PR DESCRIPTION
**Pull request by inferusvv**
ISSUE: https://github.com/aksonov/react-native-router-flux/issues/1379

### CODE REVIEW

**Comment by inferusvv** [comment]
@aksonov tests fails on `__tests__/Example-test.js`. It's ok or not?

**Comment by aksonov** [comment]
It is not ok, looks like connected with new react native version... Feel free to fix it or maybe we should fix react native version within package.json...

**Comment by inferusvv** [comment]
@aksonov Looks like it is not so ease :) I will not do it inside this PR, but if I'll have a time, I'll create a new one.

I found, that some other opened PRs also fails on that test.

**Comment by charpeni** [comment]
@inferusvv Should be fixed now, are you up to rebase on master?

**Comment by inferusvv** [comment]
@charpeni Ok, I'll do it

**Comment by inferusvv** [comment]
@charpeni Rebased

**Comment by charpeni** [comment]
Thank you.

**Comment by proProbe** [comment]
after checking out v3.37 on master, this PR seems to have been lost?

**Comment by aksonov** [comment]
Does current master contain it?

**Comment by proProbe** [comment]
no it does not

**Comment by proProbe** [comment]
Must be something weird with my node modules. It says I have 3.37 but it doesnt give me the correct src files

**Pull request merged**
