### PR TITLE
removed react-native-dependency as it will result in duplicate-module…

### PR DESCRIPTION
**Pull request by itinance**
This will fix https://github.com/aksonov/react-native-router-flux/issues/1809

For testing you can use the following line dependencies of package.json:

```
	"dependencies": {
		"react": "16.0.0-alpha.6",
		"react-native": "0.43.4",
		"react-native-router-flux": "git:github.com/itinance/react-native-router-flux#fc1b8261144fe5f3132ac4940dd794ac06e9f351"
	},

```

### CODE REVIEW

**Comment by byennen** [comment]
I recommend moving `react-native` to "devDependencies" instead of removing it totally.

**Comment by itinance** [comment]
ok, thx for the hint. Did it.

**Comment by radko93** [comment]
It's the same case with `react` dependency.

**Comment by leyuan** [comment]
Hey @itinance it seems like the `yarn.lock` file needs update too, thanks for the good work!

**Comment by itinance** [comment]
ah good to know. thanks :) i wasn't sure if i should add the yarn.lock or not

**Comment by leyuan** [comment]
@byennen why we want to keep it as a `devDependency`? I don't think it's being used anywhere..

In #1809 
> In the mean-time you can remove react-native from the node_modules folder in react-native-router-flux. however ultimately the example dependencies should be removed from the module and added to the examples package.json

If we want to keep it we should keep it as [Peer Dependency](https://yarnpkg.com/lang/en/docs/dependency-types/)

@itinance yeah sorry I didn't notice it's in dev dep right now, I mean if we want to totally remove it, we also need to remove it from lock file.. hmm not sure for now!

**Comment by itinance** [comment]
@leyuan why not :) i thought it would be used for tests via jest and the _react-test-renderer_. But to be honest i am not familiar with that

i will try another commit with removing react-dependency at all.

**Comment by leyuan** [comment]
@itinance if we keep it as a dev dep, it will still get installed into the node_modules under `react-native-router-flux` right? I think we will have two versions of react-native again..

**Comment by itinance** [comment]
But anyways, the checks fail with 

> Module ./jest/setup.js in the setupFiles option was not found.

Has this something to do with the issue that we are discussing here? i think not.

**Comment by Mikaila94** [comment]
Any update on this?

**Comment by ohtangza** [comment]
I guess this should be moved to peerDependency as submitted here: https://github.com/aksonov/react-native-router-flux/pull/1808

**Comment by msqar** [comment]
anyone knows how to fix this? i still can't use this dependency :(

**Comment by ohtangza** [comment]
Sadly, I switched back to the official react navigation, which works very good so far for me.

**Comment by aksonov** [comment]
Should be fixed now. Also v4 is released (based on new React Navigation)

**Pull request closed without merging**
