### PR TITLE
Renames Router to BaseRouter and ReactRouter to Router, and Router 'router' prop to 'plugin'

### PR DESCRIPTION
**Pull request by danielweinmann**
This PR implements what we talked about in #188.

### CODE REVIEW

**Comment by philipshurpik** [comment]
thanks!
but if it's all ok with Example now?  
As I understand it used old Router version?

possibly we need to examples - with BaseRouter and Router

**Comment by philipshurpik** [comment]
also - like a proposal - it can be good idea to clean-up index folder.
Now it' really confusing.
As a proposal: move Schema, Route, TabBar, Actions, Router, Animations to maybe 'components' folder

And ExRouter for example into 'plugins' folder

**Comment by danielweinmann** [comment]
@philipshurpik, the example uses Router because we were exporting ReactRouter as Router before. That's the good part of this refactoring: it doesn't change anything for the user of the package, only internally.

I like the ideia of having ExRouter and RouterIOS in a 'plugins' folder! :D the other classes I don't know where is a good place for them yet. @aksonov?

**Comment by aksonov** [comment]
@danielweinmann Why git shows BaseRouter as new file? I thought it show rename from Router to BaseRouter? Did you use git mv command?

**Comment by aksonov** [comment]
Also agree about moving to components all React components

**Comment by danielweinmann** [comment]
Sorry, @aksonov, I used git commit -am :S my bad.

**Comment by aksonov** [comment]
@danielweinmann Could you do it in correct way?

**Comment by danielweinmann** [comment]
Created a new PR here: https://github.com/aksonov/react-native-router-flux/pull/196

**Pull request closed without merging**
