### PR TITLE
Component prop should be optional

### PR DESCRIPTION
**Pull request by erkrapide**
The interface SceneProps should have the component prop set to optional (?), because it won't build in typescript when using a Nested Scene for Tabs. The docs claim to have this prop as and (semi)-optional.

### CODE REVIEW

**Comment by aksonov** [comment]
I can approve it, but probably it is better to make component required for `Scene` and use other container types for containers - `Tabs`, `Stack`, `Drawer`, does it make sense?

**Comment by erkrapide** [comment]
I see, you are absolutely right. I missed the `Tabs (<Tabs> or <Scene tabs>)` part. I was using `<Scene tabs>` construction.

**Comment by dernise** [comment]
Right, but shouldn't we deprecate the old syntax and update the docs to remove all the <Scene key="root"> ? It's kind of confusing for typescript users

**Comment by erkrapide** [comment]
@aksonov could you bump the version, please?

**Pull request merged**
