### PR TITLE
Adds prepublish compile step for publishing to NPM

### PR DESCRIPTION
**Pull request by cgreening**
Compile the code before pushing to NPM

https://github.com/aksonov/react-native-router-flux/issues/613
https://github.com/aksonov/react-native-router-flux/issues/628
https://github.com/aksonov/react-native-router-flux/issues/635

### CODE REVIEW

**Comment by cgreening** [comment]
I've not tested this as I can't publish this package to npm.

**Comment by charpeni** [comment]
Thanks.

We will wait for @aksonov to review it.

**Comment by lelandrichardson** [comment]
@charpeni any reason to include `src` in `.npmignore`? Can be helpful if consuming users want to look at the source code

**Comment by cgreening** [comment]
Seems to be the consensus that you ignire the src for npm and ignore the lib for git.

https://stackoverflow.com/questions/29738381/how-to-publish-a-module-written-in-es6-to-npm

I guess if you want to look at the src it's acvailable on GitHub.

**Comment by aksonov** [comment]
Looks good for me, but it makes quick fixes more difficult. Now i could change react-native-router-flux src inside my project's node_modules or Example's node_modules and then copy full src folder back to react-native-router-flux and commit. After this change i will have to do much more operations - copying src, re-compile, then test. Is there any other way to modify the component for real project quickly?

**Comment by cgreening** [comment]
Having investigated a bit further I don't think the precompile step is necessary for react native as it runs the modules through the preprocessor anyway. So we can close this pull request and ignore it.

**Comment by sattaman** [comment]
@cgreening @aksonov This is blocking me from running tests as this module throws an error due to not being transpiled when running as detailed in **https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md**. 

Can you recommend a solution?

**Comment by sathyakumarseshachalam** [comment]
Same here. I am blocked as well.

**Pull request closed without merging**
