### PR TITLE
PR for beta.8

### PR DESCRIPTION
**Pull request by aksonov**
- Fix: ‘clone’ scenes declared at the end were not visible for scenes declared above
- Enhancement: If component has static navigationOptions return it instead of RNRF generated options
- Enhancement: Allow all navBar properties (title, right, left, rightButtonImage, onRight, etc.) be defined as static functions/values of Scene component
- Fix: Actions.refresh was broken because navigationStore doesn’t allow the same scene after state change
- Enhancement: fix ESLint errors for tests
- Fix: avoid re-render of all scenes during navigation state change (#2018)
- Support rightButtonTextStyle and leftButtonTextStyle, avoid reset them to default values after push (after push from Login to Login2, "Cancel" became blue again)
- Fix: Support passing navbar attributes (like onRight/onLeft/leftTitle/rightTitle) via `Actions.refresh`
- Fix: postinstall somewhere doesn't work with npm (#2008)

### CODE REVIEW

**Comment by compojoom** [comment]
@aksonov - how is this fixing the actions.refresh?  I downloaded the 4.0.8 branch and launched the example, but I still can't change the title on the login page. 

The same happens in a separate project as well.

**Comment by aksonov** [comment]
@compojoom Please check now (forgot to 'build' js)

**Comment by compojoom** [comment]
@aksonov - it seems to partially work. It's changing the title, but nothing more? I was used to the folowing pattern in v3:

```js
componentDidMount() {
		console.log('wtffff refressshshhh');
		let title = 'Analyse1',
			rightTitle = 'Speichern';

		if (this.props.editMode) {
			title = 'Analyse Bearbeiten';
			rightTitle = 'Fertig';
		}
		Actions.refresh({
			title: title,
			rightTitle: rightTitle,
			onRight: () => this.onRight(),
			backTitle: 'Abbrechen',
		});
	}
```

this seems to work now, but the only thing changing is the title. No right button appears in my navbar.

**Comment by compojoom** [comment]
Hm, okay. Defining onRight and rightTitle on my scene seems to work together with refresh. If I define them on the scene, refresh will override them, but if I don't define them, then nothing happens. I don't see any right button.

**Comment by aksonov** [comment]
@compojoom Please check with latest commit.

**Comment by southerneer** [comment]
I tried adding static nav options on Register.js and they weren't overriding the RNRF options...

```js
class Register extends React.Component {
  static navigationOptions = {
    title: 'Hello',
    headerRight: <Text>Right?</Text>,
    headerTintColor: 'blue',
  }

  render = () => (
    <View style={styles.container}>
      <Text>Register page</Text>
      <Button onPress={()=>Actions.register2()}>Register2</Button>
      <Button onPress={Actions.home}>Replace screen</Button>
      <Button onPress={Actions.pop}>Back</Button>
    </View>
  );
}
```

image

**Comment by southerneer** [comment]
I put the Echo view at the bottom of the router component to test clones and RNRF choked on the `JSON.stringify` call. When I commented it out it worked great...adding a commit.

**Comment by southerneer** [comment]
All the other changes/fixes seemed to work for me!

**Comment by compojoom** [comment]
I'm wondering if anyone else is experiencing this:
grafik
I just open and re-save the image, but I don't understand why this happens at all.

**Comment by compojoom** [comment]
@aksonov - if the scene doesn't have onright and rightTitle, then the refresh action isn't working. (tested with latest version)

**Comment by aksonov** [comment]
@compojoom Please give me link to forked Example to demonstrate.

**Comment by aksonov** [comment]
@southerneer Thanks!

**Comment by aksonov** [comment]
@compojoom Never mind, was able to reproduce with your snippet above

**Comment by compojoom** [comment]
@aksonov - you were faster https://github.com/compojoom/react-native-router-flux/tree/4.0.0-beta.8-no-refresh

**Comment by aksonov** [comment]
@compojoom Check now

**Comment by aksonov** [comment]
About burger image, use Issues search. Like #703

**Comment by compojoom** [comment]
woooohoooo! Let's open the champagne bottle for PR8 👍

**Comment by aksonov** [comment]
@compojoom Thanks for testing!

**Pull request merged**
