### PR TITLE
Fix eslint src/Navbar.js

### PR DESCRIPTION
**Pull request by charpeni**
Related to #567

### CODE REVIEW

**Comment by aksonov** [comment]
@charpeni ops, sorry, enabled os x plan but it didn't run because it is paid! for open source! reverted back, could you submit another PR to run build again? Maybe we must use travisci instead with os x support for free (we could build Example project and run GUI tests for it!)

**Comment by charpeni** [comment]
TravisCI is really slow, but I like your idea. Maybe we could setup TravisCI only for OS X build and keep CircleCI for Eslint and Mocha ?

**Comment by aksonov** [comment]
Ugh, circleci schedules new builds, and don't want to remove 'os x' ones. I'm removing it and re-adding the project again...

**Comment by aksonov** [comment]
Yes, we could try both

**Pull request merged**
