### PR TITLE
app bar height

### PR DESCRIPTION
**Pull request by jeroenbourgois**
Just a easy fix to switch app bar height on Android / iOS. Not sure if this is sufficient....

### CODE REVIEW

**Comment by chzhuo** [comment]
There be a problem. When android version is greater than 21, we can set component StatusBar is translucent.   When translucent is set to true, the app will draw under the status bar. This is useful when using a semi transparent status bar color. So should provide a api to control if  the nav bar height is 44 or 64. 
you can see [react-native #6876](https://github.com/facebook/react-native/issues/6876)

**Comment by aksonov** [comment]
Sorry it doesn't work (for iOS), i've reverted it
simulator screen shot 27 apr 2016 09 05 22

**Comment by chzhuo** [comment]
@jeroenbourgois You code have a bug, should be 'Platform.OS', not 'Platform.os' in NavBar.js line 205

**Comment by Kerumen** [comment]
@aksonov It doesn't work because it should be `Platform.OS` and not `Platform.os`. As it's `undefined` you get the Android's height in both platform.

**Comment by aksonov** [comment]
Ok, you might submit correct PR and change version within package json

Pavel.

**Comment by Kerumen** [comment]
Ok I'm creating a PR with appropriate fixes also for the buttons and title position.

**Comment by sarovin** [comment]
There is an issue with android api > 17...

Please FIX with:

```
title: {
    top: Platform.OS === 'ios' || Platform.Version > 19 ? 20 : 0,
  },
  header: {
    height: Platform.OS === 'ios' || Platform.Version > 19 ? 64 : 44,
  },
![without fix](https://cloud.githubusercontent.com/assets/5980398/14915850/381fed7c-0e16-11e6-8f70-b2e7f67ab802.png)
![with fix](https://cloud.githubusercontent.com/assets/5980398/14915851/3824e836-0e16-11e6-8424-b709a263f247.png)


```

**Comment by sarovin** [comment]
#614

**Comment by edencakir** [comment]
@sarovin can you please elaborate the `Platform.version > 19` part? What about < 18, what does that mean?

**Pull request merged**
