### PR TITLE
Add `hideDrawerButton` prop to Drawer

### PR DESCRIPTION
**Pull request by mvanroon**
This allows for people to hide the toggle Drawer button so that they may add a custom button somewhere else (I have one in my TabBar)

schermafbeelding 2017-10-07 om 12 55 00

### CODE REVIEW

**Comment by aksonov** [comment]
Nice PR, could you add that new property to docs?

**Comment by mvanroon** [comment]
It's already in the docs mate

**Comment by aksonov** [comment]
Could you give me a link?

**Comment by mvanroon** [comment]
https://github.com/aksonov/react-native-router-flux/pull/2473/files#diff-96cc378dcdef180641176501f42183c7

**Comment by aksonov** [comment]
Sorry, my fault. Thanks!

**Comment by remch1990** [comment]
how i cant put a button in the tabbar to open and close the drawer? like the image.  RNRF V4

**Comment by mvanroon** [comment]
it's a custom implementation; I've built my own `tabBarComponent` and added a button that `onPress` calls `drawerOpen`. Please refer to gitter or stackoverflow is you have any other questions

**Pull request merged**
