### PR TITLE
fix routes not initialized on parent componentDidMount

### PR DESCRIPTION
**Pull request by atlanteh**
Since setState is async then on componentDidMount of parent the router is not initialized yet and running Actions.someRouter() results in Actions.callback is not defined exception.

### CODE REVIEW

**Comment by atlanteh** [comment]
#686

**Comment by atlanteh** [comment]
guys any update regarding this?

**Comment by joenoon** [comment]
@atlanteh I've looked at this diff and read through the comments on https://github.com/aksonov/react-native-router-flux/issues/686 

I'm pretty sure this is a matter of moving the code that calls Actions.foo() into the right spot.  It looks like right now at least from the original issue, Actions.foo() is being attempted in a parent and is expecting its children to execute (create the reducer) before it can function, which is against how the react component lifecycle works.

This probably means using a Switch to handle the scene picking in the context of the router and its lifecycle.  Or at the very least moving the Actions.foo() to a component used *by* the router, not in the component that is responsible for creating the router.

**Comment by atlanteh** [comment]
@joenoon
Actually, I ran into that problem because I ran into the same one.Calling an action in rnrf parent's componentDidMount results in an error. We choose the screen dynamicly, so we call different routes on componentDidMount. It's expected that the router is initialized when it's mounted and it's not. Only after the router is mounted it starts to initialize itself *asynchronously*, which means we have no idea when it's safe to call an action.
It makes no sense that we must set arbitrary timeout in hopes that the router is initialized after it, and currently this is the conculsion of #686.
My PR makes sure that once the router is mounted it's also initialized.
This allows the parent to call an actions on componentDidMount.

**Comment by joenoon** [comment]
@atlanteh a couple thoughts:

First, I'm not against the PR as long as people have tested it.  I'm currently way behind versions so I can't test this on my app.  Hopefully @aksonov and others can review.

But some other thoughts: `Actions` tends to get treated like a singleton, yet Router is not.  This has always been an oddity/bug IMO, but most of the time people don't run into issues because they use only one Router.  But really, I don't think there should be a global `Actions`.  If the router exposed a `actions` method and passed that down either through context or props, then the situation here would be more clear.  You would need to access `this.props.actions` which would make it obvious where `actions` is available.  I'm not sure, but I would hope that would take the async/race issues out of this.

If you do want to treat `Actions` as a singleton, then my suggestion would be to define your actions all up front:

```
const scenes = Actions.create(
  <Scene key="root" hideNavBar hideTabBar>
    ... scenes ...
  </Scene>
);

export const MyRouter = function (props) {
  return <Router key="router" scenes={scenes} ... />;
}
```

Again, not sure if that would fix this specific problem, but just throwing ideas out there.

**Comment by atlanteh** [comment]
@joenoon, the problem is not the routes not being initialized, they actually are initialized synchronously. The problem is the router itself.
You see, Actions.callback is only defined in [renderNavigation](https://github.com/aksonov/react-native-router-flux/blob/master/src/Router.js#L128).
The problem is, that renderNavigation is called only after [this.state.reducer](https://github.com/aksonov/react-native-router-flux/blob/master/src/Router.js#L144).
So using Actions as a singleton or not, this problem is not solved.

**Comment by atlanteh** [comment]
Ok, so I just cloned my repository with the change and it seems to work great with your example. I even played a little bit with hot loading and changing names & backgrounds and it doesn't seem to break any functionality. You can try it by cloning:
git clone -b "patch-1" https://git@github.com/atlanteh/react-native-router-flux.git
and then trying your example.
It would help a lot if the guys from #686 can try it and confirm it's working.
@dominicmh, @rturk @charpeni @aksonov @dwilt @shilpan
Can you guys help?

**Comment by joenoon** [comment]
I just pulled this down and tried it in my app.  I couldn't really do much to test it since there is a pretty bad bug in master that seems to be wiping out the tab bar, making master basically broken.  (Anyone know what happened there?)

I have a feeling by looking at the changes that this is ok.  And worst case, it won't be the only blocker on master.  I'll give it a few hours and then merge this unless anyone objects before then.

**Comment by chetstone** [comment]
@joenoon I discussed the tab bar regression in issue #1151 . I identified the offending commit. This is a pretty serious problem that has not been addressed.

**Comment by aksonov** [comment]
Ok, let's revert it

Pavel.

**Comment by dwilt** [comment]
Are you reverting this fix or something else not related to this ticket?

**Comment by aksonov** [comment]
@dwilt Regression made https://github.com/aksonov/react-native-router-flux/issues/1151

**Comment by dwilt** [comment]
@aksonov I'm confused. So are you saying this commit (https://github.com/aksonov/react-native-router-flux/commit/492a1171b8606869e5808f48220e7b0df4699c88) that got merged caused a regression (https://github.com/aksonov/react-native-router-flux/issues/1151) and you're going to revert this merge?

Not arguing, just want to make sure I understand what is going on and if I need to revert this patch in our project.

**Comment by aksonov** [comment]
@dwilt Check that comment ("@joenoon I discussed the tab bar regression in issue #1151 . I identified the offending commit. This is a pretty serious problem that has not been addressed.")

@charpeni, @joenoon Looks like @chetstone is not available, could you look? We can't publish new release because of that bug...

**Pull request merged**
