### PR TITLE
Added section about Relay support with example app

### PR DESCRIPTION
**Pull request by r0b1n**
As asked in this issue: https://github.com/aksonov/react-native-router-flux/issues/437
Added section about Relay.

### CODE REVIEW

**Comment by rturk** [comment]
@r0b1n fantastic. However I would really like to see tests and ideally working examples before declaring relay supported.

**Comment by r0b1n** [comment]
@rturk got you, thanks. Will improve an example app.

**Comment by Lenin7** [comment]
@r0b1n Did the example ended up not working?

**Comment by r0b1n** [comment]
@Lenin7 I havn't checked this example for a long time since I am not working on `react-native` + `relay` myself.

But last time it was working.Have you checked it recently?

Also there is bit complex example in https://github.com/r0b1n/rnrf-relay-example/tree/hotels-backend branch which is working with this `graphql` backend example https://github.com/r0b1n/graphql-hotels-example

I am happy to update these examples, but don't have a time right now.

**Pull request closed without merging**
