### PR TITLE
Whitelist event listeners to prevent "scene 'on...' is not defined" warning

### PR DESCRIPTION
**Pull request by kesha-antonov**
Hello!

When I open a scene with ```Actions.scene({ onUpdateSmth: this.myFunc })``` or ```Actions.scene({ onUpdateSmth: undefined })``` I get ```scene "onUpdateSmth" is not defined```.

We should use whitelist for events that starts with ```on```.

### CODE REVIEW

**Comment by onrige** [comment]
Hey. Could you remove package-lock from this PR, please?

**Comment by kesha-antonov** [comment]
Why? It's not in gitignore and it's good practice to keep .lock files.
@onrige

**Comment by onrige** [comment]
Sure, but we use yarn (also for this). You can add package-lock to gitignore in commit if you want :)

**Comment by aksonov** [comment]
Please check latest master now. I fixed it in different way because you PR would break other functionality (like custom transition shortcuts like onLogin='loginScene')

**Comment by kesha-antonov** [comment]
Ok. Thanks! @aksonov 
Works without PR

**Pull request closed without merging**
