### PR TITLE
Fix crash when unmounting WrappedComponent

### PR DESCRIPTION
**Pull request by wsxyeah**
Check if has routeName to prevent crash

### CODE REVIEW

**Comment by mcabs3** [comment]
Do you have an example of what would cause this crash?

**Comment by wsxyeah** [comment]
@mcabs3 Yes.

Add a `key` for the container in Example.js (just like the `LightBox`).
Then choose the RN menu `Toggle Inspector` on the device, you will see the crash.

```javascript
<Router>
  <Modal>
    <LightBox key="lightbox_top"> // here
      <Stack key="root"/>
      // other scenes …
    </LightBox>
  </Modal>
</Router>
```

**Comment by wsxyeah** [comment]
@mcabs3 Oh, I found the root cause now.

Sine the `OverlayNavigator` passed wrong `state` to its child overlay components, the children will never get `this.props.navigation.state.routeName`.

**Comment by mcabs3** [comment]
@wsxyeah so is this change irrelevant now?

**Pull request closed without merging**
