### PR TITLE
Fix android back error

### PR DESCRIPTION
**Pull request by Swordsman-Inaction**
The old way to implement android back handler will raise an issue described in #1165

This PR will fix this by create a special action just for android back action.

@cuitianze @Micjoyce Can you test this a little bit, to make sure this does fix the issue on your project?

### CODE REVIEW

**Comment by Micjoyce** [comment]
[There is a demo for test,](https://github.com/Micjoyce/rn-route-flux-demo/tree/master) sounds work well.

**Comment by Swordsman-Inaction** [comment]
@aksonov @charpeni Do I have to past the CI? Seems the Example test configuration has some problem.

**Comment by Swordsman-Inaction** [comment]
Seems like the CI has been disabled. Can we merge this PR now? @charpeni

**Comment by aksonov** [comment]
I’ve re-added circleci support, please check now

**Comment by Swordsman-Inaction** [comment]
@aksonov It didn't run

**Comment by aksonov** [comment]
I see, this circleci makes me crazy.

**Comment by Swordsman-Inaction** [comment]
@aksonov Why don't use Travis CI? At lease Travis CI provides `Restart Build` function so I don't need to commit useless commits. LOL

**Comment by hortonelectric** [comment]
+1 can someone merge this please. It's affecting a lot of things.

**Comment by aksonov** [comment]
@Swordsman-Inaction Could you setup travis CI?

**Comment by Swordsman-Inaction** [comment]
@aksonov I'll start the setup this week.

**Pull request merged**
