### PR TITLE
Closes #3267 #3258: Fix replace and issues with refresh

### LINKED ISSUE #3267: Add Expo example and move examples do its own folder
With the addition the `Expo` example, it's becoming a bit messy all these examples over the lib folder. Moving it to its own folder and also adding some code to help with development/test code generation.

### PR DESCRIPTION
**Pull request by daviscabral**
All code from this PR was moved to other PRs - the fix was removed, but I'll brought it back in a few.

### CODE REVIEW

**Comment by daviscabral** [comment]
@aksonov Probably going to break this into smaller PRs - but just to give a heads up why the fix from other PR took so long.

**Comment by aksonov** [comment]
Looks huuuge, but anyway, good job!

**Comment by aksonov** [comment]
Yes, we need to split it to smaller PR

**Comment by daviscabral** [comment]
I'll push smaller PRs in a few. 

@aksonov Is there any way that we could talk/chat? Sometimes I feel that would work fast for a few decisions/directions that I am taking that might not be good for the project.

I am available on skype (id: daviscabral), whatsapp (if you also use it - email me with your number at daviscabral@gmail.com so we might talk over there), Telegram (id: daviscabral) and on gitter (already started a chat with you there a few days ago).

**Comment by daviscabral** [comment]
@aksonov done!

**Pull request merged**
