### PR TITLE
add typings

### PR DESCRIPTION
**Pull request by bang88**
Hello

Can i add a typing for RNRF,Thanks.

### CODE REVIEW

**Comment by rturk** [comment]
Hi @bang88 are you also plaining to maintain this? My sense is that this will break quite often given the number of changes that React and RNRF will experience in the upcoming releases.

**Comment by charpeni** [comment]
@rturk Totally agree.

I don't know for the other collaborators, but I'll prefer [Flow](http://flowtype.org/) type checker instead of TypeScript.

**Comment by bang88** [comment]
@rturk  That's fine,but i think if you guys found an issue in typings you can improve it,not just me.
@charpeni  I don't want choose Flow or typescript,just give this a try for lntellisense when use https://code.visualstudio.com/

Accept or not your choice. I am free.

**Comment by joenoon** [comment]
I like this even though it means a little more maintenance.  It can only really be maintained by people who use vscode or something else that interprets these typing files.  So it might break or be outdated from time to time, but thats better than not including it IMO.

**Comment by rturk** [comment]
@joenoon makes sense. Worse case scenario this will only affect folks using vscode, and it will be always another tool to validade the code.

**Pull request merged**
