### PR TITLE
Move react deps to peerDeps, fixes #1803

### LINKED ISSUE #1803: Duplicate versions of react-native being installed
react-native-router-flux v3.38.1
react-native v0.42.3

yarn install is causing react-native v0.42.3 and react-native v0.41.1 to be installed

Should react and react-native be installed as a peerDependency for react-native-router-flux?

To repro:

react-native init {projectName}  --version=0.42.3
cd {projectName}
yarn add react-native-router-flux
npm start

You should see
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/bdewitt/sandbox/break/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/bdewitt/sandbox/break/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-animated
  Paths: /Users/bdewitt/sandbox/break/node_modules/react-native-router-flux/node_modules/react-native/Libraries/Animated/release/package.json collides with /Users/bdewitt/sandbox/break/node_modules/react-native/Libraries/Animated/release/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/bdewitt/sandbox/break/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/bdewitt/sandbox/break/node_modules/react-native/packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

yarn add react-native-router-flux@3.38.0

Should succeed

### PR DESCRIPTION
**Pull request by stensrud**

### CODE REVIEW

**Comment by saidmoya12** [comment]
Still this problem.

Why no is implemented yet?

**Comment by ohtangza** [comment]
This is very important for some project because it is causing the following error:

screen shot 2017-05-03 at 10 41 34 pm

**Comment by duhseekoh** [comment]
How has this not been merged? And a better question, how did react-native and react ever make it into the project as regular dependencies?

**Comment by aksonov** [comment]
Should be fixed now

**Pull request closed without merging**
