### PR TITLE
Fix bug hideNavBar not working

### PR DESCRIPTION
**Pull request by donnguyen**
The place we put hideNavBar checking just makes no sense so move it above the other rendering code lines

### CODE REVIEW

**Comment by cridenour** [comment]
The tests failed in an upstream library - weird. This LGTM.

**Comment by charpeni** [comment]
@cridenour This is because the branch `0.24` doesn't contain a `circle.yml`. In fact, that commit should not rather be merged in master?

**Comment by cridenour** [comment]
@charpeni Good catch. Should this be master or 0.26-wip?

**Comment by joenoon** [comment]
This wont apply to 0.26-wip since the check is done quite a bit differently there

**Comment by joenoon** [comment]
Closing since 3.24 is no longer supported.  Please reopen against master if there is still an issue.

**Comment by eranbes** [comment]
hideNavBar={true} does not work in 0.26. 
I have this
 <Scene key="startup" initial={true} hideNavBar={true} /> yet it shows the navbar

**Pull request closed without merging**
