### PR TITLE
use alt's magic method

### PR DESCRIPTION
**Pull request by daemonchen**
use alt's magic method

### CODE REVIEW

**Comment by aksonov** [comment]
Will it work if some actions are not handled, like 'switch' action inside store.js ?

**Comment by daemonchen** [comment]
In alt, there is no switch statement, does it ?

**Comment by aksonov** [comment]
Sorry, i meant ContainerStore which adds 'switch' action. Also user may add 'custom' actions, so store.js cannot handle all actions.

**Comment by daemonchen** [comment]
Oh, I think it can handle all user's 'custom' action in 'onCustom' way.

**Pull request closed without merging**
